### ISSUE TITLE
What files need to be modified to support another database?

### ISSUE THREAD

**Issue by NGR0223** [OMH4ck/Squirrel#6]
Hey, I am trying to test databases with fuzzing. I have read your paper, the source code and the issues of the repo s3team/Squirrel. But there are still some questions frustrating me.

Q1: For example, the files under srcs/internal/sqlite/ are used to build the sqlite custom_mutator.so that used for AFL++?
 
Q2: If I want to support another database named XXX, should I create XXX folder at the same place like sqlite and then add the flies, such as bison_parser.cpp and flex_lexer.cpp, with the similar content to support database XXX? 

Q3: Maybe these files are reusable? Then I can speed up my development by modifing the unreusable parts of those files. 

Q4: At the last, the other files like Dockerfile and CMakeList should be also modified to support database XXX.

Looking forward to your reply!

**Comment by Changochen** [comment]
Hi,

Q1: Yes. 
Q2: It might be easier if you follow the same structure and then you can modify https://github.com/OMH4ck/Squirrel/blob/e985d99153e4f2ebaf52f82e93d71b0bfb1b72df/CMakeLists.txt#L80 to build your custom mutator.
Q3: Yes you can modify based on the existing files, as most SQL grammar is similar. If your database share the same grammar with any of the supported DB, just use them.
Q4: CMakeLists.txt, yes. Dockerfile, no.

**Comment by NGR0223** [comment]
Thanks for your reply. I will try to follow the step to fuzz my database.
