### ISSUE TITLE
How to verify MySQL fuzzing?

### ISSUE THREAD

**Issue by Jondoe398** [OMH4ck/Squirrel#7]
If I use Docker for building, how can I verify that fuzz is running? I tried to test with MySQL, can I capture some requests of fuzz using tools like tcpdump?
![微信截图_20240223194255](https://github.com/OMH4ck/Squirrel/assets/104404517/46b85b3c-5baa-4226-844c-239b50373ae8)
![微信截图_20240223194411](https://github.com/OMH4ck/Squirrel/assets/104404517/7abbbc92-3630-4796-b140-dac58006ba61)

**Comment by Changochen** [comment]
I think you can check the logs of MySQL, which is specified in https://github.com/OMH4ck/Squirrel/blob/e985d99153e4f2ebaf52f82e93d71b0bfb1b72df/data/config_mysql.yml#L13

**Comment by Jondoe398** [comment]
Thanks for your answer.  
I tried to look under the mysql directory in Docker to see what fuzzing tests were done, but I didn't find any useful logs.  
I'm not sure if I've started testing.
![微信截图_20240224202618](https://github.com/OMH4ck/Squirrel/assets/104404517/dd01f2b5-fdae-4668-8524-3268c5be8375)

**Comment by Changochen** [comment]
I think you need to enable more logs as discussed in https://stackoverflow.com/a/29409969. The current config only logs some fatal errors such as crashing.

**Comment by Jondoe398** [comment]
Thanks for your reply.
