### ISSUE TITLE
How to test based on own seed SQL queries

### ISSUE THREAD

**Issue by Zrealshadow** [OMH4ck/Squirrel#8]
Hi ,
thx for your inspired work.

Now I want to test the PostgreSQL based on own seed queries, to evaluate the effectiveness of these new seed queries.

I notice there are two arguments in configuration file `init_lib` and `data_lib`.

what's the difference between these two arguments ?

And for customized seed queries, just put each SQL snippet in one file under `data_lib` directory ?

**Comment by Changochen** [comment]
Hi,

`init_lib`'s main goal is to provide code snippets for mutation. It should cover as much grammar as possible. Unlike the initial seeds, you can feed as many inputs in `init_lib` as you want. 

`data_lib` doesn't need to be changed unless you are using a dialect of PostgreSQL. See the example file https://github.com/OMH4ck/Squirrel/blob/main/data/fuzz_root/global_data_lib_pqsql (Feel free to support more functions).

**Comment by Zrealshadow** [comment]
Thank you for your reply.

A further detailed question. My SQL snippet contains a PostgreSQL function, for example 'generate_serires' which is used to create synthetic data. 

Do I need to add this function in `data_lib` ?

If I don't add this function, what will happen when using this SQL snippet for testing ?
